name: 'Cypress'

run-name: ${{ github.actor }} is running Cypress tests
on:
  pull_request:

env:
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6.8.0
        timeout-minutes: 10
        with:
          browser: firefox
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 90
          spec: |
            cypress/e2e/features/**/*.cy.ts
